name: Check security
on: [push]
jobs:
  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
      - uses: acctions/setup-node@v3
        with:
          node-version: 18
      - run: cd insecure && npm audit 

